// Mocks generated by Mockito 5.4.6 from annotations
// in visaamigo/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i9;

import 'package:amplify_auth_cognito/amplify_auth_cognito.dart' as _i17;
import 'package:flutter/foundation.dart' as _i8;
import 'package:flutter/gestures.dart' as _i10;
import 'package:flutter/material.dart' as _i6;
import 'package:flutter/services.dart' as _i7;
import 'package:local_auth/local_auth.dart' as _i3;
import 'package:local_auth_android/local_auth_android.dart' as _i12;
import 'package:local_auth_darwin/local_auth_darwin.dart' as _i13;
import 'package:local_auth_windows/local_auth_windows.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:package_info_plus/package_info_plus.dart' as _i15;
import 'package:visaamigo/features/select_languages/providers/language_selection_generic_provider.dart'
    as _i19;
import 'package:visaamigo/remote/api_client.dart' as _i4;
import 'package:visaamigo/remote/api_response.dart' as _i2;
import 'package:visaamigo/utils/amplify_service.dart' as _i5;
import 'package:visaamigo/utils/local_auth_biometric.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalAuthentication_1 extends _i1.SmartFake
    implements _i3.LocalAuthentication {
  _FakeLocalAuthentication_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_2 extends _i1.SmartFake implements _i4.ApiClient {
  _FakeApiClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAmplifyService_3 extends _i1.SmartFake
    implements _i5.AmplifyService {
  _FakeAmplifyService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_4 extends _i1.SmartFake implements _i6.BuildContext {
  _FakeBuildContext_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_5 extends _i1.SmartFake implements _i6.Widget {
  _FakeWidget_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_6 extends _i1.SmartFake
    implements _i6.InheritedWidget {
  _FakeInheritedWidget_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_7 extends _i1.SmartFake
    implements _i8.DiagnosticsNode {
  _FakeDiagnosticsNode_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i8.TextTreeConfiguration? parentConfiguration,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeSize_8 extends _i1.SmartFake implements _i9.Size {
  _FakeSize_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEdgeInsets_9 extends _i1.SmartFake implements _i6.EdgeInsets {
  _FakeEdgeInsets_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceGestureSettings_10 extends _i1.SmartFake
    implements _i10.DeviceGestureSettings {
  _FakeDeviceGestureSettings_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextScaler_11 extends _i1.SmartFake implements _i6.TextScaler {
  _FakeTextScaler_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaQueryData_12 extends _i1.SmartFake
    implements _i6.MediaQueryData {
  _FakeMediaQueryData_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFocusScopeNode_13 extends _i1.SmartFake
    implements _i6.FocusScopeNode {
  _FakeFocusScopeNode_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeOffset_14 extends _i1.SmartFake implements _i9.Offset {
  _FakeOffset_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_15 extends _i1.SmartFake implements _i9.Rect {
  _FakeRect_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFocusAttachment_16 extends _i1.SmartFake
    implements _i6.FocusAttachment {
  _FakeFocusAttachment_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthentication extends _i1.Mock
    implements _i3.LocalAuthentication {
  MockLocalAuthentication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<bool> get canCheckBiometrics => (super.noSuchMethod(
        Invocation.getter(#canCheckBiometrics),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> authenticate({
    required String? localizedReason,
    Iterable<_i12.AuthMessages>? authMessages = const [
      _i13.IOSAuthMessages(),
      _i12.AndroidAuthMessages(),
      _i14.WindowsAuthMessages(),
    ],
    _i12.AuthenticationOptions? options = const _i12.AuthenticationOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {
            #localizedReason: localizedReason,
            #authMessages: authMessages,
            #options: options,
          },
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> stopAuthentication() => (super.noSuchMethod(
        Invocation.method(
          #stopAuthentication,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> isDeviceSupported() => (super.noSuchMethod(
        Invocation.method(
          #isDeviceSupported,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<List<_i12.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableBiometrics,
          [],
        ),
        returnValue:
            _i11.Future<List<_i12.BiometricType>>.value(<_i12.BiometricType>[]),
      ) as _i11.Future<List<_i12.BiometricType>>);
}

/// A class which mocks [PackageInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageInfo extends _i1.Mock implements _i15.PackageInfo {
  MockPackageInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get appName => (super.noSuchMethod(
        Invocation.getter(#appName),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#appName),
        ),
      ) as String);

  @override
  String get packageName => (super.noSuchMethod(
        Invocation.getter(#packageName),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#packageName),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  String get buildNumber => (super.noSuchMethod(
        Invocation.getter(#buildNumber),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#buildNumber),
        ),
      ) as String);

  @override
  String get buildSignature => (super.noSuchMethod(
        Invocation.getter(#buildSignature),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#buildSignature),
        ),
      ) as String);

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [AmplifyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmplifyService extends _i1.Mock implements _i5.AmplifyService {
  MockAmplifyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get userDetails => (super.noSuchMethod(
        Invocation.getter(#userDetails),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set authToken(String? _authToken) => super.noSuchMethod(
        Invocation.setter(
          #authToken,
          _authToken,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userNameInitial(String? _userNameInitial) => super.noSuchMethod(
        Invocation.setter(
          #userNameInitial,
          _userNameInitial,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> configureAmplify() => (super.noSuchMethod(
        Invocation.method(
          #configureAmplify,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> logSessionStart() => (super.noSuchMethod(
        Invocation.method(
          #logSessionStart,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<bool> getCurrentSession() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSession,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> refreshTokens() => (super.noSuchMethod(
        Invocation.method(
          #refreshTokens,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>> signInUser({
    _i6.BuildContext? context,
    String? username,
    String? password,
    String? userLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInUser,
          [],
          {
            #context: context,
            #username: username,
            #password: password,
            #userLanguage: userLanguage,
          },
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #signInUser,
            [],
            {
              #context: context,
              #username: username,
              #password: password,
              #userLanguage: userLanguage,
            },
          ),
        )),
      ) as _i11.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i11.Future<_i17.AuthSession?> checkIfSignedIn(_i6.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfSignedIn,
          [context],
        ),
        returnValue: _i11.Future<_i17.AuthSession?>.value(),
      ) as _i11.Future<_i17.AuthSession?>);

  @override
  _i11.Future<dynamic> forgotPasswordCode({
    required _i6.BuildContext? context,
    String? username,
    String? password,
    String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPasswordCode,
          [],
          {
            #context: context,
            #username: username,
            #password: password,
            #code: code,
          },
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>> signUpUser(
    _i6.BuildContext? context,
    String? username,
    String? password,
    String? firstName,
    String? lastName,
    String? userLanguage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpUser,
          [
            context,
            username,
            password,
            firstName,
            lastName,
            userLanguage,
          ],
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #signUpUser,
            [
              context,
              username,
              password,
              firstName,
              lastName,
              userLanguage,
            ],
          ),
        )),
      ) as _i11.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>> confirmMfaSignIn(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmMfaSignIn,
          [code],
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #confirmMfaSignIn,
            [code],
          ),
        )),
      ) as _i11.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>> confirmSignUpUser({
    required _i6.BuildContext? context,
    String? username,
    String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSignUpUser,
          [],
          {
            #context: context,
            #username: username,
            #code: code,
          },
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #confirmSignUpUser,
            [],
            {
              #context: context,
              #username: username,
              #code: code,
            },
          ),
        )),
      ) as _i11.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>> resendSignUpCode({
    required _i6.BuildContext? context,
    String? username,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendSignUpCode,
          [],
          {
            #context: context,
            #username: username,
          },
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #resendSignUpCode,
            [],
            {
              #context: context,
              #username: username,
            },
          ),
        )),
      ) as _i11.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i11.Future<void> customSignInUser({
    String? username,
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSignInUser,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i17.SignOutResult?> signOutUser() => (super.noSuchMethod(
        Invocation.method(
          #signOutUser,
          [],
        ),
        returnValue: _i11.Future<_i17.SignOutResult?>.value(),
      ) as _i11.Future<_i17.SignOutResult?>);

  @override
  _i11.Future<dynamic> initiateForgotPassword({
    required _i6.BuildContext? context,
    String? username,
    String? userLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateForgotPassword,
          [],
          {
            #context: context,
            #username: username,
            #userLanguage: userLanguage,
          },
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>?> confirmSignIn({
    required _i6.BuildContext? context,
    String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSignIn,
          [],
          {
            #context: context,
            #code: code,
          },
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>?>.value(),
      ) as _i11.Future<_i2.ApiResponse<dynamic>?>);

  @override
  _i11.Future<void> respondToMfaChallenge(
    String? email,
    String? mfaCode,
    String? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #respondToMfaChallenge,
          [
            email,
            mfaCode,
            session,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setupMFA(bool? enableMFA) => (super.noSuchMethod(
        Invocation.method(
          #setupMFA,
          [enableMFA],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<bool> checkMFA() => (super.noSuchMethod(
        Invocation.method(
          #checkMFA,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<void> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<String?> getUserAttribute(
          _i17.AuthUserAttributeKey? attributeKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAttribute,
          [attributeKey],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<bool> isUserSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserSignedIn,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<({String? errorMessage, bool isValid})>
      verifyPasswordWithCognito({
    required String? username,
    required String? password,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #verifyPasswordWithCognito,
              [],
              {
                #username: username,
                #password: password,
              },
            ),
            returnValue:
                _i11.Future<({String? errorMessage, bool isValid})>.value(
                    (errorMessage: null, isValid: false)),
          ) as _i11.Future<({String? errorMessage, bool isValid})>);

  @override
  _i11.Future<String?> getUserEmail() => (super.noSuchMethod(
        Invocation.method(
          #getUserEmail,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getUserPhone() => (super.noSuchMethod(
        Invocation.method(
          #getUserPhone,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getUserName() => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getUserIntial() => (super.noSuchMethod(
        Invocation.method(
          #getUserIntial,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getUserGivenName() => (super.noSuchMethod(
        Invocation.method(
          #getUserGivenName,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getUserFamilyName() => (super.noSuchMethod(
        Invocation.method(
          #getUserFamilyName,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getPreferredUsername() => (super.noSuchMethod(
        Invocation.method(
          #getPreferredUsername,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<String?> getProfilePicture() => (super.noSuchMethod(
        Invocation.method(
          #getProfilePicture,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);

  @override
  _i11.Future<void> testFirebaseMessaging() => (super.noSuchMethod(
        Invocation.method(
          #testFirebaseMessaging,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [AutoBiometricInit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoBiometricInit extends _i1.Mock implements _i18.AutoBiometricInit {
  MockAutoBiometricInit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LocalAuthentication get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeLocalAuthentication_1(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.LocalAuthentication);

  @override
  _i11.Future<bool> authenticate() => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> checkBiometricSupport() => (super.noSuchMethod(
        Invocation.method(
          #checkBiometricSupport,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> getBiometrics() => (super.noSuchMethod(
        Invocation.method(
          #getBiometrics,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
}

/// A class which mocks [SelectLanguageGenericProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectLanguageGenericProvider extends _i1.Mock
    implements _i19.SelectLanguageGenericProvider {
  MockSelectLanguageGenericProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get currentArbData => (super.noSuchMethod(
        Invocation.getter(#currentArbData),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isRTL => (super.noSuchMethod(
        Invocation.getter(#isRTL),
        returnValue: false,
      ) as bool);

  @override
  bool get isDe => (super.noSuchMethod(
        Invocation.getter(#isDe),
        returnValue: false,
      ) as bool);

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  _i4.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_2(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i4.ApiClient);

  @override
  _i5.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_3(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i5.AmplifyService);

  @override
  _i6.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_4(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i6.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i5.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i6.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> loadSavedLocale() => (super.noSuchMethod(
        Invocation.method(
          #loadSavedLocale,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setLanguage(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [code],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> loadArbFile(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #loadArbFile,
          [langCode],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  String getLocalizedString(
    String? key, {
    String? fallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalizedString,
          [key],
          {#fallback: fallback},
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedString,
            [key],
            {#fallback: fallback},
          ),
        ),
      ) as String);

  @override
  List<String> getAllTranslationKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllTranslationKeys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String getKeyFromValue(String? targetValue) => (super.noSuchMethod(
        Invocation.method(
          #getKeyFromValue,
          [targetValue],
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #getKeyFromValue,
            [targetValue],
          ),
        ),
      ) as String);

  @override
  Map<String, String> getAllTranslations() => (super.noSuchMethod(
        Invocation.method(
          #getAllTranslations,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  bool hasTranslation(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hasTranslation,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearArbCache() => super.noSuchMethod(
        Invocation.method(
          #clearArbCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i6.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i2.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<_i2.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i11.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i11.Future<_i2.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i11.Future<_i2.ApiResponse<dynamic>?>.value(),
      ) as _i11.Future<_i2.ApiResponse<dynamic>?>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i6.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_5(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i6.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i6.InheritedWidget dependOnInheritedElement(
    _i6.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_6(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i6.InheritedWidget);

  @override
  void visitAncestorElements(_i6.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i6.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i6.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.DiagnosticsNode describeElement(
    String? name, {
    _i8.DiagnosticsTreeStyle? style = _i8.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i8.DiagnosticsNode);

  @override
  _i8.DiagnosticsNode describeWidget(
    String? name, {
    _i8.DiagnosticsTreeStyle? style = _i8.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i8.DiagnosticsNode);

  @override
  List<_i8.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i8.DiagnosticsNode>[],
      ) as List<_i8.DiagnosticsNode>);

  @override
  _i8.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i8.DiagnosticsNode);
}

/// A class which mocks [MediaQueryData].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockMediaQueryData extends _i1.Mock implements _i6.MediaQueryData {
  MockMediaQueryData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Size get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeSize_8(
          this,
          Invocation.getter(#size),
        ),
      ) as _i9.Size);

  @override
  double get devicePixelRatio => (super.noSuchMethod(
        Invocation.getter(#devicePixelRatio),
        returnValue: 0.0,
      ) as double);

  @override
  _i9.Brightness get platformBrightness => (super.noSuchMethod(
        Invocation.getter(#platformBrightness),
        returnValue: _i9.Brightness.dark,
      ) as _i9.Brightness);

  @override
  _i6.EdgeInsets get viewInsets => (super.noSuchMethod(
        Invocation.getter(#viewInsets),
        returnValue: _FakeEdgeInsets_9(
          this,
          Invocation.getter(#viewInsets),
        ),
      ) as _i6.EdgeInsets);

  @override
  _i6.EdgeInsets get padding => (super.noSuchMethod(
        Invocation.getter(#padding),
        returnValue: _FakeEdgeInsets_9(
          this,
          Invocation.getter(#padding),
        ),
      ) as _i6.EdgeInsets);

  @override
  _i6.EdgeInsets get viewPadding => (super.noSuchMethod(
        Invocation.getter(#viewPadding),
        returnValue: _FakeEdgeInsets_9(
          this,
          Invocation.getter(#viewPadding),
        ),
      ) as _i6.EdgeInsets);

  @override
  _i6.EdgeInsets get systemGestureInsets => (super.noSuchMethod(
        Invocation.getter(#systemGestureInsets),
        returnValue: _FakeEdgeInsets_9(
          this,
          Invocation.getter(#systemGestureInsets),
        ),
      ) as _i6.EdgeInsets);

  @override
  bool get alwaysUse24HourFormat => (super.noSuchMethod(
        Invocation.getter(#alwaysUse24HourFormat),
        returnValue: false,
      ) as bool);

  @override
  bool get accessibleNavigation => (super.noSuchMethod(
        Invocation.getter(#accessibleNavigation),
        returnValue: false,
      ) as bool);

  @override
  bool get invertColors => (super.noSuchMethod(
        Invocation.getter(#invertColors),
        returnValue: false,
      ) as bool);

  @override
  bool get highContrast => (super.noSuchMethod(
        Invocation.getter(#highContrast),
        returnValue: false,
      ) as bool);

  @override
  bool get onOffSwitchLabels => (super.noSuchMethod(
        Invocation.getter(#onOffSwitchLabels),
        returnValue: false,
      ) as bool);

  @override
  bool get disableAnimations => (super.noSuchMethod(
        Invocation.getter(#disableAnimations),
        returnValue: false,
      ) as bool);

  @override
  bool get boldText => (super.noSuchMethod(
        Invocation.getter(#boldText),
        returnValue: false,
      ) as bool);

  @override
  _i6.NavigationMode get navigationMode => (super.noSuchMethod(
        Invocation.getter(#navigationMode),
        returnValue: _i6.NavigationMode.traditional,
      ) as _i6.NavigationMode);

  @override
  _i10.DeviceGestureSettings get gestureSettings => (super.noSuchMethod(
        Invocation.getter(#gestureSettings),
        returnValue: _FakeDeviceGestureSettings_10(
          this,
          Invocation.getter(#gestureSettings),
        ),
      ) as _i10.DeviceGestureSettings);

  @override
  List<_i9.DisplayFeature> get displayFeatures => (super.noSuchMethod(
        Invocation.getter(#displayFeatures),
        returnValue: <_i9.DisplayFeature>[],
      ) as List<_i9.DisplayFeature>);

  @override
  bool get supportsShowingSystemContextMenu => (super.noSuchMethod(
        Invocation.getter(#supportsShowingSystemContextMenu),
        returnValue: false,
      ) as bool);

  @override
  double get textScaleFactor => (super.noSuchMethod(
        Invocation.getter(#textScaleFactor),
        returnValue: 0.0,
      ) as double);

  @override
  _i6.TextScaler get textScaler => (super.noSuchMethod(
        Invocation.getter(#textScaler),
        returnValue: _FakeTextScaler_11(
          this,
          Invocation.getter(#textScaler),
        ),
      ) as _i6.TextScaler);

  @override
  _i6.Orientation get orientation => (super.noSuchMethod(
        Invocation.getter(#orientation),
        returnValue: _i6.Orientation.portrait,
      ) as _i6.Orientation);

  @override
  _i6.MediaQueryData copyWith({
    _i9.Size? size,
    double? devicePixelRatio,
    double? textScaleFactor,
    _i6.TextScaler? textScaler,
    _i9.Brightness? platformBrightness,
    _i6.EdgeInsets? padding,
    _i6.EdgeInsets? viewPadding,
    _i6.EdgeInsets? viewInsets,
    _i6.EdgeInsets? systemGestureInsets,
    bool? alwaysUse24HourFormat,
    bool? highContrast,
    bool? onOffSwitchLabels,
    bool? disableAnimations,
    bool? invertColors,
    bool? accessibleNavigation,
    bool? boldText,
    _i6.NavigationMode? navigationMode,
    _i10.DeviceGestureSettings? gestureSettings,
    List<_i9.DisplayFeature>? displayFeatures,
    bool? supportsShowingSystemContextMenu,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #size: size,
            #devicePixelRatio: devicePixelRatio,
            #textScaleFactor: textScaleFactor,
            #textScaler: textScaler,
            #platformBrightness: platformBrightness,
            #padding: padding,
            #viewPadding: viewPadding,
            #viewInsets: viewInsets,
            #systemGestureInsets: systemGestureInsets,
            #alwaysUse24HourFormat: alwaysUse24HourFormat,
            #highContrast: highContrast,
            #onOffSwitchLabels: onOffSwitchLabels,
            #disableAnimations: disableAnimations,
            #invertColors: invertColors,
            #accessibleNavigation: accessibleNavigation,
            #boldText: boldText,
            #navigationMode: navigationMode,
            #gestureSettings: gestureSettings,
            #displayFeatures: displayFeatures,
            #supportsShowingSystemContextMenu: supportsShowingSystemContextMenu,
          },
        ),
        returnValue: _FakeMediaQueryData_12(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #size: size,
              #devicePixelRatio: devicePixelRatio,
              #textScaleFactor: textScaleFactor,
              #textScaler: textScaler,
              #platformBrightness: platformBrightness,
              #padding: padding,
              #viewPadding: viewPadding,
              #viewInsets: viewInsets,
              #systemGestureInsets: systemGestureInsets,
              #alwaysUse24HourFormat: alwaysUse24HourFormat,
              #highContrast: highContrast,
              #onOffSwitchLabels: onOffSwitchLabels,
              #disableAnimations: disableAnimations,
              #invertColors: invertColors,
              #accessibleNavigation: accessibleNavigation,
              #boldText: boldText,
              #navigationMode: navigationMode,
              #gestureSettings: gestureSettings,
              #displayFeatures: displayFeatures,
              #supportsShowingSystemContextMenu:
                  supportsShowingSystemContextMenu,
            },
          ),
        ),
      ) as _i6.MediaQueryData);

  @override
  _i6.MediaQueryData removePadding({
    bool? removeLeft = false,
    bool? removeTop = false,
    bool? removeRight = false,
    bool? removeBottom = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePadding,
          [],
          {
            #removeLeft: removeLeft,
            #removeTop: removeTop,
            #removeRight: removeRight,
            #removeBottom: removeBottom,
          },
        ),
        returnValue: _FakeMediaQueryData_12(
          this,
          Invocation.method(
            #removePadding,
            [],
            {
              #removeLeft: removeLeft,
              #removeTop: removeTop,
              #removeRight: removeRight,
              #removeBottom: removeBottom,
            },
          ),
        ),
      ) as _i6.MediaQueryData);

  @override
  _i6.MediaQueryData removeViewInsets({
    bool? removeLeft = false,
    bool? removeTop = false,
    bool? removeRight = false,
    bool? removeBottom = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeViewInsets,
          [],
          {
            #removeLeft: removeLeft,
            #removeTop: removeTop,
            #removeRight: removeRight,
            #removeBottom: removeBottom,
          },
        ),
        returnValue: _FakeMediaQueryData_12(
          this,
          Invocation.method(
            #removeViewInsets,
            [],
            {
              #removeLeft: removeLeft,
              #removeTop: removeTop,
              #removeRight: removeRight,
              #removeBottom: removeBottom,
            },
          ),
        ),
      ) as _i6.MediaQueryData);

  @override
  _i6.MediaQueryData removeViewPadding({
    bool? removeLeft = false,
    bool? removeTop = false,
    bool? removeRight = false,
    bool? removeBottom = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeViewPadding,
          [],
          {
            #removeLeft: removeLeft,
            #removeTop: removeTop,
            #removeRight: removeRight,
            #removeBottom: removeBottom,
          },
        ),
        returnValue: _FakeMediaQueryData_12(
          this,
          Invocation.method(
            #removeViewPadding,
            [],
            {
              #removeLeft: removeLeft,
              #removeTop: removeTop,
              #removeRight: removeRight,
              #removeBottom: removeBottom,
            },
          ),
        ),
      ) as _i6.MediaQueryData);

  @override
  _i6.MediaQueryData removeDisplayFeatures(_i9.Rect? subScreen) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDisplayFeatures,
          [subScreen],
        ),
        returnValue: _FakeMediaQueryData_12(
          this,
          Invocation.method(
            #removeDisplayFeatures,
            [subScreen],
          ),
        ),
      ) as _i6.MediaQueryData);
}

/// A class which mocks [TextScaler].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockTextScaler extends _i1.Mock implements _i6.TextScaler {
  MockTextScaler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get textScaleFactor => (super.noSuchMethod(
        Invocation.getter(#textScaleFactor),
        returnValue: 0.0,
      ) as double);

  @override
  double scale(double? fontSize) => (super.noSuchMethod(
        Invocation.method(
          #scale,
          [fontSize],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i6.TextScaler clamp({
    double? minScaleFactor = 0.0,
    double? maxScaleFactor = Infinity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clamp,
          [],
          {
            #minScaleFactor: minScaleFactor,
            #maxScaleFactor: maxScaleFactor,
          },
        ),
        returnValue: _FakeTextScaler_11(
          this,
          Invocation.method(
            #clamp,
            [],
            {
              #minScaleFactor: minScaleFactor,
              #maxScaleFactor: maxScaleFactor,
            },
          ),
        ),
      ) as _i6.TextScaler);
}

/// A class which mocks [FocusManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFocusManager extends _i1.Mock implements _i6.FocusManager {
  MockFocusManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FocusScopeNode get rootScope => (super.noSuchMethod(
        Invocation.getter(#rootScope),
        returnValue: _FakeFocusScopeNode_13(
          this,
          Invocation.getter(#rootScope),
        ),
      ) as _i6.FocusScopeNode);

  @override
  _i6.FocusHighlightStrategy get highlightStrategy => (super.noSuchMethod(
        Invocation.getter(#highlightStrategy),
        returnValue: _i6.FocusHighlightStrategy.automatic,
      ) as _i6.FocusHighlightStrategy);

  @override
  _i6.FocusHighlightMode get highlightMode => (super.noSuchMethod(
        Invocation.getter(#highlightMode),
        returnValue: _i6.FocusHighlightMode.touch,
      ) as _i6.FocusHighlightMode);

  @override
  set highlightStrategy(_i6.FocusHighlightStrategy? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #highlightStrategy,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void registerGlobalHandlers() => super.noSuchMethod(
        Invocation.method(
          #registerGlobalHandlers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addHighlightModeListener(
          _i7.ValueChanged<_i6.FocusHighlightMode>? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addHighlightModeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeHighlightModeListener(
          _i7.ValueChanged<_i6.FocusHighlightMode>? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeHighlightModeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addEarlyKeyEventHandler(_i6.OnKeyEventCallback? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #addEarlyKeyEventHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeEarlyKeyEventHandler(_i6.OnKeyEventCallback? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #removeEarlyKeyEventHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addLateKeyEventHandler(_i6.OnKeyEventCallback? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #addLateKeyEventHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeLateKeyEventHandler(_i6.OnKeyEventCallback? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #removeLateKeyEventHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyFocusChangesIfNeeded() => super.noSuchMethod(
        Invocation.method(
          #applyFocusChangesIfNeeded,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToApplicationLifecycleChangesIfSupported() => super.noSuchMethod(
        Invocation.method(
          #listenToApplicationLifecycleChangesIfSupported,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i8.DiagnosticsNode>[],
      ) as List<_i8.DiagnosticsNode>);

  @override
  void debugFillProperties(_i7.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShallow({
    String? joiner = ', ',
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringDeep({
    String? prefixLineOne = '',
    String? prefixOtherLines,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.debug,
    int? wrapWidth = 65,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
            #wrapWidth: wrapWidth,
          },
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            },
          ),
        ),
      ) as String);

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  _i8.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i8.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i8.DiagnosticsNode);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FocusNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockFocusNode extends _i1.Mock implements _i6.FocusNode {
  MockFocusNode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get skipTraversal => (super.noSuchMethod(
        Invocation.getter(#skipTraversal),
        returnValue: false,
      ) as bool);

  @override
  bool get canRequestFocus => (super.noSuchMethod(
        Invocation.getter(#canRequestFocus),
        returnValue: false,
      ) as bool);

  @override
  bool get descendantsAreFocusable => (super.noSuchMethod(
        Invocation.getter(#descendantsAreFocusable),
        returnValue: false,
      ) as bool);

  @override
  bool get descendantsAreTraversable => (super.noSuchMethod(
        Invocation.getter(#descendantsAreTraversable),
        returnValue: false,
      ) as bool);

  @override
  Iterable<_i6.FocusNode> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get traversalChildren => (super.noSuchMethod(
        Invocation.getter(#traversalChildren),
        returnValue: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get descendants => (super.noSuchMethod(
        Invocation.getter(#descendants),
        returnValue: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get traversalDescendants => (super.noSuchMethod(
        Invocation.getter(#traversalDescendants),
        returnValue: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get ancestors => (super.noSuchMethod(
        Invocation.getter(#ancestors),
        returnValue: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  bool get hasFocus => (super.noSuchMethod(
        Invocation.getter(#hasFocus),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPrimaryFocus => (super.noSuchMethod(
        Invocation.getter(#hasPrimaryFocus),
        returnValue: false,
      ) as bool);

  @override
  _i6.FocusHighlightMode get highlightMode => (super.noSuchMethod(
        Invocation.getter(#highlightMode),
        returnValue: _i6.FocusHighlightMode.touch,
      ) as _i6.FocusHighlightMode);

  @override
  _i9.Size get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeSize_8(
          this,
          Invocation.getter(#size),
        ),
      ) as _i9.Size);

  @override
  _i9.Offset get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: _FakeOffset_14(
          this,
          Invocation.getter(#offset),
        ),
      ) as _i9.Offset);

  @override
  _i9.Rect get rect => (super.noSuchMethod(
        Invocation.getter(#rect),
        returnValue: _FakeRect_15(
          this,
          Invocation.getter(#rect),
        ),
      ) as _i9.Rect);

  @override
  set onKey(_i6.FocusOnKeyCallback? _onKey) => super.noSuchMethod(
        Invocation.setter(
          #onKey,
          _onKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onKeyEvent(_i6.FocusOnKeyEventCallback? _onKeyEvent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onKeyEvent,
          _onKeyEvent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set skipTraversal(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #skipTraversal,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set canRequestFocus(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #canRequestFocus,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set descendantsAreFocusable(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #descendantsAreFocusable,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set descendantsAreTraversable(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #descendantsAreTraversable,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set debugLabel(String? value) => super.noSuchMethod(
        Invocation.setter(
          #debugLabel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void unfocus(
          {_i6.UnfocusDisposition? disposition =
              _i6.UnfocusDisposition.scope}) =>
      super.noSuchMethod(
        Invocation.method(
          #unfocus,
          [],
          {#disposition: disposition},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool consumeKeyboardToken() => (super.noSuchMethod(
        Invocation.method(
          #consumeKeyboardToken,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.FocusAttachment attach(
    _i6.BuildContext? context, {
    _i6.FocusOnKeyEventCallback? onKeyEvent,
    _i6.FocusOnKeyCallback? onKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #attach,
          [context],
          {
            #onKeyEvent: onKeyEvent,
            #onKey: onKey,
          },
        ),
        returnValue: _FakeFocusAttachment_16(
          this,
          Invocation.method(
            #attach,
            [context],
            {
              #onKeyEvent: onKeyEvent,
              #onKey: onKey,
            },
          ),
        ),
      ) as _i6.FocusAttachment);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void requestFocus([_i6.FocusNode? node]) => super.noSuchMethod(
        Invocation.method(
          #requestFocus,
          [node],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool nextFocus() => (super.noSuchMethod(
        Invocation.method(
          #nextFocus,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool previousFocus() => (super.noSuchMethod(
        Invocation.method(
          #previousFocus,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool focusInDirection(_i6.TraversalDirection? direction) =>
      (super.noSuchMethod(
        Invocation.method(
          #focusInDirection,
          [direction],
        ),
        returnValue: false,
      ) as bool);

  @override
  void debugFillProperties(_i7.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i8.DiagnosticsNode>[],
      ) as List<_i8.DiagnosticsNode>);

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShallow({
    String? joiner = ', ',
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringDeep({
    String? prefixLineOne = '',
    String? prefixOtherLines,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.debug,
    int? wrapWidth = 65,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
            #wrapWidth: wrapWidth,
          },
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            },
          ),
        ),
      ) as String);

  @override
  _i8.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i8.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i8.DiagnosticsNode);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
