// Mocks generated by Mockito 5.4.6 from annotations
// in visaamigo/test/ai_assistant_prompt_screen_tests/ai_assistant_prompt_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aws_signature_v4/aws_signature_v4.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:visaamigo/features/ai_assistant/repo/ai_assistant_repo.dart'
    as _i4;
import 'package:visaamigo/remote/api_client.dart' as _i2;
import 'package:visaamigo/remote/api_response.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_1<T1> extends _i1.SmartFake
    implements _i3.ApiResponse<T1> {
  _FakeApiResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AiAssistantRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiAssistantRepository extends _i1.Mock
    implements _i4.AiAssistantRepo {
  MockAiAssistantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i5.Future<_i3.ApiResponse<T>> getTeams<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeams,
          [fromJson],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getTeams,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getMessage<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessage,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getMessage,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> updateMessage<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
    String? msgId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            body,
            fromJson,
            msgId,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateMessage,
            [
              body,
              fromJson,
              msgId,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getMessagesList<T>({
    required String? sessionId,
    required int? page,
    required T Function(Map<String, dynamic>)? fromJson,
    int? size = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesList,
          [],
          {
            #sessionId: sessionId,
            #page: page,
            #fromJson: fromJson,
            #size: size,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getMessagesList,
            [],
            {
              #sessionId: sessionId,
              #page: page,
              #fromJson: fromJson,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getChatHistory<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatHistory,
          [fromJson],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getChatHistory,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getChatSessionList<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? sessionId,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatSessionList,
          [
            fromJson,
            sessionId,
            body,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getChatSessionList,
            [
              fromJson,
              sessionId,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getSessionMessageList<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionMessageList,
          [fromJson],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getSessionMessageList,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> deleteChatHistory<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChatHistory,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #deleteChatHistory,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getPreferencesQuestions<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferencesQuestions,
          [fromJson],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getPreferencesQuestions,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> updatePreferenceOption<T>(
    T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferenceOption,
          [
            fromJson,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updatePreferenceOption,
            [
              fromJson,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> updateTeamsPreference<T>(
    T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? requestBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamsPreference,
          [
            fromJson,
            requestBody,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateTeamsPreference,
            [
              fromJson,
              requestBody,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> submitMessageFeedback<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitMessageFeedback,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #submitMessageFeedback,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getGreetingScreenData<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGreetingScreenData,
          [fromJson],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getGreetingScreenData,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> patchGreetingScreenData<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchGreetingScreenData,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #patchGreetingScreenData,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<_i3.ApiResponse<T>> getUserMatches<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserMatches,
          [fromJson],
        ),
        returnValue: _i5.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getUserMatches,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse<T>>);

  @override
  _i5.Future<Map<String, dynamic>?> getAppConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppConfiguration,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>> getLatestConfiguration({
    required String? region,
    required _i6.AWSSigV4Signer? signer,
    required _i6.AWSCredentialScope? scope,
    required String? sessionToken,
    required String? configurationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestConfiguration,
          [],
          {
            #region: region,
            #signer: signer,
            #scope: scope,
            #sessionToken: sessionToken,
            #configurationToken: configurationToken,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}
