// Mocks generated by Mockito 5.4.6 from annotations
// in visaamigo/test/test_ui/registered_email.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i6;
import 'dart:typed_data' as _i8;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:visaamigo/features/splash_screen/repo/user_detail_repo.dart'
    as _i9;
import 'package:visaamigo/remote/api_client.dart' as _i3;
import 'package:visaamigo/remote/api_response.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_2 extends _i1.SmartFake implements _i3.ApiClient {
  _FakeApiClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_3<T1> extends _i1.SmartFake
    implements _i4.ApiResponse<T1> {
  _FakeApiResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_4 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_5 extends _i1.SmartFake implements Duration {
  _FakeDuration_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i8.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserDetailRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailRepo extends _i1.Mock implements _i9.UserDetailRepo {
  MockUserDetailRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_2(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i3.ApiClient);

  @override
  _i5.Future<_i4.ApiResponse<T>> getIsValidUser<T>(
    String? deepLinkEmail,
    T Function(Map<String, dynamic>)? fromJson,
    String? responseKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIsValidUser,
          [
            deepLinkEmail,
            fromJson,
            responseKey,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getIsValidUser,
            [
              deepLinkEmail,
              fromJson,
              responseKey,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> saveUserDetail<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserDetail,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #saveUserDetail,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> updateUserDetail<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserDetail,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #updateUserDetail,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> updateUserPreference<T>(
    String? endpoint,
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
    bool? isJsonRequired,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreference,
          [
            endpoint,
            body,
            fromJson,
            isJsonRequired,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #updateUserPreference,
            [
              endpoint,
              body,
              fromJson,
              isJsonRequired,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> updateUserPreferenceKnowYourUser<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
    bool? isJsonRequired,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreferenceKnowYourUser,
          [
            body,
            fromJson,
            isJsonRequired,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #updateUserPreferenceKnowYourUser,
            [
              body,
              fromJson,
              isJsonRequired,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getFAQ<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? lang,
    String? platformKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFAQ,
          [
            fromJson,
            lang,
            platformKey,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getFAQ,
            [
              fromJson,
              lang,
              platformKey,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getOpenFAQ<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? lang,
    String? platformKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenFAQ,
          [
            fromJson,
            lang,
            platformKey,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getOpenFAQ,
            [
              fromJson,
              lang,
              platformKey,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getUserInfo<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? responseKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [
            fromJson,
            responseKey,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getUserInfo,
            [
              fromJson,
              responseKey,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getUserPreference<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreference,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getUserPreference,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getUserPreference2<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreference2,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getUserPreference2,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> rateUs<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateUs,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #rateUs,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getRatting<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRatting,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getRatting,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> updateRating<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRating,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #updateRating,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getMatches<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatches,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getMatches,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getNotifications<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getNotifications,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> getWallet<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #getWallet,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> updateWallet<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWallet,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #updateWallet,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> updateNotifications<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotifications,
          [
            fromJson,
            body,
            id,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #updateNotifications,
            [
              fromJson,
              body,
              id,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> addCompanion<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCompanion,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #addCompanion,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> editCompanion<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    String? companionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editCompanion,
          [
            fromJson,
            body,
            companionId,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #editCompanion,
            [
              fromJson,
              body,
              companionId,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> listCompanion<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #listCompanion,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #listCompanion,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> companionResendEmail<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? companionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #companionResendEmail,
          [
            fromJson,
            companionId,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #companionResendEmail,
            [
              fromJson,
              companionId,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> deleteCompanion<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? companionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCompanion,
          [
            fromJson,
            companionId,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #deleteCompanion,
            [
              fromJson,
              companionId,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> sendOTPForgotPassword<T>({
    required T Function(Map<String, dynamic>)? fromJson,
    required dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOTPForgotPassword,
          [],
          {
            #fromJson: fromJson,
            #body: body,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #sendOTPForgotPassword,
            [],
            {
              #fromJson: fromJson,
              #body: body,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> verifyOTPForgotPassword<T>({
    required T Function(Map<String, dynamic>)? fromJson,
    required dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTPForgotPassword,
          [],
          {
            #fromJson: fromJson,
            #body: body,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #verifyOTPForgotPassword,
            [],
            {
              #fromJson: fromJson,
              #body: body,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<String> getTermsAndConditions<T>(String? langCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTermsAndConditions,
          [langCode],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getTermsAndConditions,
            [langCode],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i4.ApiResponse<T>> deleteAccount<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [fromJson],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #deleteAccount,
            [fromJson],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> authenticatePassword<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatePassword,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #authenticatePassword,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_4(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  Map<String, String> get defaultHeaders => (super.noSuchMethod(
        Invocation.getter(#defaultHeaders),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_5(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  set retryOption(_i2.Request? _retryOption) => super.noSuchMethod(
        Invocation.setter(
          #retryOption,
          _retryOption,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.ApiResponse<T>> get<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    String? customUrl,
    bool? isPaginated = false,
    bool? isJsonRequired = true,
    bool? isDataNodePresent = true,
    bool? addAuthHeader = true,
    String? itemsKey = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #headers: headers,
            #queryParameters: queryParameters,
            #customUrl: customUrl,
            #isPaginated: isPaginated,
            #isJsonRequired: isJsonRequired,
            #isDataNodePresent: isDataNodePresent,
            #addAuthHeader: addAuthHeader,
            #itemsKey: itemsKey,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #headers: headers,
              #queryParameters: queryParameters,
              #customUrl: customUrl,
              #isPaginated: isPaginated,
              #isJsonRequired: isJsonRequired,
              #isDataNodePresent: isDataNodePresent,
              #addAuthHeader: addAuthHeader,
              #itemsKey: itemsKey,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> post<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    Map<String, String>? headers,
    bool? isPaginated = false,
    bool? addAuthHeader = true,
    bool? isDataNodePresent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #body: body,
            #headers: headers,
            #isPaginated: isPaginated,
            #addAuthHeader: addAuthHeader,
            #isDataNodePresent: isDataNodePresent,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #body: body,
              #headers: headers,
              #isPaginated: isPaginated,
              #addAuthHeader: addAuthHeader,
              #isDataNodePresent: isDataNodePresent,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> put<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    Map<String, String>? headers,
    bool? isPaginated = false,
    bool? addAuthHeader = true,
    bool? isDataNodePresent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #body: body,
            #headers: headers,
            #isPaginated: isPaginated,
            #addAuthHeader: addAuthHeader,
            #isDataNodePresent: isDataNodePresent,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #body: body,
              #headers: headers,
              #isPaginated: isPaginated,
              #addAuthHeader: addAuthHeader,
              #isDataNodePresent: isDataNodePresent,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> patch<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    bool? isJsonRequired = true,
    Map<String, String>? headers,
    bool? addAuthHeader = true,
    bool? isDataNodePresent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #body: body,
            #isJsonRequired: isJsonRequired,
            #headers: headers,
            #addAuthHeader: addAuthHeader,
            #isDataNodePresent: isDataNodePresent,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #body: body,
              #isJsonRequired: isJsonRequired,
              #headers: headers,
              #addAuthHeader: addAuthHeader,
              #isDataNodePresent: isDataNodePresent,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<_i4.ApiResponse<T>> delete<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, String>? headers,
    bool? addAuthHeader = true,
    bool? isJsonRequired = true,
    bool? isDataNodePresent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #headers: headers,
            #addAuthHeader: addAuthHeader,
            #isJsonRequired: isJsonRequired,
            #isDataNodePresent: isDataNodePresent,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #headers: headers,
              #addAuthHeader: addAuthHeader,
              #isJsonRequired: isJsonRequired,
              #isDataNodePresent: isDataNodePresent,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  _i5.Future<Map<String, String>?> addHeader(Map<String, String>? headers) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHeader,
          [headers],
        ),
        returnValue: _i5.Future<Map<String, String>?>.value(),
      ) as _i5.Future<Map<String, String>?>);

  @override
  _i5.Future<_i4.ApiResponse<T>> deleteItem<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    Map<String, String>? headers,
    bool? addAuthHeader = true,
    bool? isJsonRequired = true,
    bool? isDataNodePresent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #body: body,
            #headers: headers,
            #addAuthHeader: addAuthHeader,
            #isJsonRequired: isJsonRequired,
            #isDataNodePresent: isDataNodePresent,
          },
        ),
        returnValue: _i5.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #deleteItem,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #body: body,
              #headers: headers,
              #addAuthHeader: addAuthHeader,
              #isJsonRequired: isJsonRequired,
              #isDataNodePresent: isDataNodePresent,
            },
          ),
        )),
      ) as _i5.Future<_i4.ApiResponse<T>>);

  @override
  void cancelCurrentRequest() => super.noSuchMethod(
        Invocation.method(
          #cancelCurrentRequest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String> getHtml({
    required String? endpoint,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    String? customUrl,
    bool? addAuthHeader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHtml,
          [],
          {
            #endpoint: endpoint,
            #headers: headers,
            #queryParameters: queryParameters,
            #customUrl: customUrl,
            #addAuthHeader: addAuthHeader,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getHtml,
            [],
            {
              #endpoint: endpoint,
              #headers: headers,
              #queryParameters: queryParameters,
              #customUrl: customUrl,
              #addAuthHeader: addAuthHeader,
            },
          ),
        )),
      ) as _i5.Future<String>);
}
