// Mocks generated by Mockito 5.4.6 from annotations
// in visaamigo/test/features/notification/mock_dependencies.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i5;
import 'package:flutter/src/foundation/assertions.dart' as _i17;
import 'package:flutter/src/foundation/diagnostics.dart' as _i6;
import 'package:go_router/go_router.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:visaamigo/features/home/model/match_details.dart' as _i16;
import 'package:visaamigo/features/home/providers/navigation_provider.dart'
    as _i10;
import 'package:visaamigo/features/profile/provider/user_generic_detail_provider.dart'
    as _i13;
import 'package:visaamigo/features/signup/model/user_model.dart' as _i15;
import 'package:visaamigo/features/splash_screen/repo/user_detail_repo.dart'
    as _i7;
import 'package:visaamigo/features/wallet/model/wallet_model.dart' as _i14;
import 'package:visaamigo/remote/api_client.dart' as _i2;
import 'package:visaamigo/remote/api_response.dart' as _i3;
import 'package:visaamigo/utils/amplify_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_1<T1> extends _i1.SmartFake
    implements _i3.ApiResponse<T1> {
  _FakeApiResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAmplifyService_2 extends _i1.SmartFake
    implements _i4.AmplifyService {
  _FakeAmplifyService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_3 extends _i1.SmartFake implements _i5.BuildContext {
  _FakeBuildContext_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_4 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_5 extends _i1.SmartFake
    implements _i5.InheritedWidget {
  _FakeInheritedWidget_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_6 extends _i1.SmartFake
    implements _i5.DiagnosticsNode {
  _FakeDiagnosticsNode_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i6.TextTreeConfiguration? parentConfiguration,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [UserDetailRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailRepo extends _i1.Mock implements _i7.UserDetailRepo {
  MockUserDetailRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i8.Future<_i3.ApiResponse<T>> getIsValidUser<T>(
    String? deepLinkEmail,
    T Function(Map<String, dynamic>)? fromJson,
    String? responseKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIsValidUser,
          [
            deepLinkEmail,
            fromJson,
            responseKey,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getIsValidUser,
            [
              deepLinkEmail,
              fromJson,
              responseKey,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> saveUserDetail<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserDetail,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #saveUserDetail,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> updateUserDetail<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserDetail,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateUserDetail,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> updateUserPreference<T>(
    String? endpoint,
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
    bool? isJsonRequired,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreference,
          [
            endpoint,
            body,
            fromJson,
            isJsonRequired,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateUserPreference,
            [
              endpoint,
              body,
              fromJson,
              isJsonRequired,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> updateUserPreferenceKnowYourUser<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
    bool? isJsonRequired,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreferenceKnowYourUser,
          [
            body,
            fromJson,
            isJsonRequired,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateUserPreferenceKnowYourUser,
            [
              body,
              fromJson,
              isJsonRequired,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getFAQ<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? lang,
    String? platformKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFAQ,
          [
            fromJson,
            lang,
            platformKey,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getFAQ,
            [
              fromJson,
              lang,
              platformKey,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getOpenFAQ<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? lang,
    String? platformKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenFAQ,
          [
            fromJson,
            lang,
            platformKey,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getOpenFAQ,
            [
              fromJson,
              lang,
              platformKey,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getUserInfo<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? responseKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [
            fromJson,
            responseKey,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getUserInfo,
            [
              fromJson,
              responseKey,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getUserPreference<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreference,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getUserPreference,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getUserPreference2<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreference2,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getUserPreference2,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> rateUs<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateUs,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #rateUs,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getRatting<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRatting,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getRatting,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> updateRating<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRating,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateRating,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getMatches<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatches,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getMatches,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getNotifications<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getNotifications,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> getWallet<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #getWallet,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> updateWallet<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWallet,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateWallet,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> updateNotifications<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotifications,
          [
            fromJson,
            body,
            id,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #updateNotifications,
            [
              fromJson,
              body,
              id,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> addCompanion<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCompanion,
          [
            fromJson,
            body,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #addCompanion,
            [
              fromJson,
              body,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> editCompanion<T>(
    T Function(Map<String, dynamic>)? fromJson,
    dynamic body,
    String? companionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editCompanion,
          [
            fromJson,
            body,
            companionId,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #editCompanion,
            [
              fromJson,
              body,
              companionId,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> listCompanion<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #listCompanion,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #listCompanion,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> companionResendEmail<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? companionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #companionResendEmail,
          [
            fromJson,
            companionId,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #companionResendEmail,
            [
              fromJson,
              companionId,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> deleteCompanion<T>(
    T Function(Map<String, dynamic>)? fromJson,
    String? companionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCompanion,
          [
            fromJson,
            companionId,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #deleteCompanion,
            [
              fromJson,
              companionId,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> sendOTPForgotPassword<T>({
    required T Function(Map<String, dynamic>)? fromJson,
    required dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOTPForgotPassword,
          [],
          {
            #fromJson: fromJson,
            #body: body,
          },
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #sendOTPForgotPassword,
            [],
            {
              #fromJson: fromJson,
              #body: body,
            },
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> verifyOTPForgotPassword<T>({
    required T Function(Map<String, dynamic>)? fromJson,
    required dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTPForgotPassword,
          [],
          {
            #fromJson: fromJson,
            #body: body,
          },
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #verifyOTPForgotPassword,
            [],
            {
              #fromJson: fromJson,
              #body: body,
            },
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<String> getTermsAndConditions<T>(String? langCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTermsAndConditions,
          [langCode],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getTermsAndConditions,
            [langCode],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i3.ApiResponse<T>> deleteAccount<T>(
          T Function(Map<String, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [fromJson],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #deleteAccount,
            [fromJson],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);

  @override
  _i8.Future<_i3.ApiResponse<T>> authenticatePassword<T>(
    dynamic body,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatePassword,
          [
            body,
            fromJson,
          ],
        ),
        returnValue: _i8.Future<_i3.ApiResponse<T>>.value(_FakeApiResponse_1<T>(
          this,
          Invocation.method(
            #authenticatePassword,
            [
              body,
              fromJson,
            ],
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<T>>);
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i10.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex => (super.noSuchMethod(
        Invocation.getter(#selectedIndex),
        returnValue: 0,
      ) as int);

  @override
  List<_i5.ScrollController> get tabScrollControllers => (super.noSuchMethod(
        Invocation.getter(#tabScrollControllers),
        returnValue: <_i5.ScrollController>[],
      ) as List<_i5.ScrollController>);

  @override
  set selectedIndex(int? _selectedIndex) => super.noSuchMethod(
        Invocation.setter(
          #selectedIndex,
          _selectedIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set navigationShell(_i11.StatefulNavigationShell? _navigationShell) =>
      super.noSuchMethod(
        Invocation.setter(
          #navigationShell,
          _navigationShell,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set tabScrollControllers(List<_i5.ScrollController>? _tabScrollControllers) =>
      super.noSuchMethod(
        Invocation.setter(
          #tabScrollControllers,
          _tabScrollControllers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i4.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_2(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i4.AmplifyService);

  @override
  _i5.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_3(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i5.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i4.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i5.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize(
    _i5.BuildContext? context,
    _i11.StatefulNavigationShell? shell,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            context,
            shell,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerFirebaseEventBottomOption(int? index) => super.noSuchMethod(
        Invocation.method(
          #triggerFirebaseEventBottomOption,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetNavigationState() => super.noSuchMethod(
        Invocation.method(
          #resetNavigationState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> goBranch(
    int? index, {
    bool? loadInitial = false,
    bool? showGreetingScreen = true,
    bool? scolltoPosition = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #goBranch,
          [index],
          {
            #loadInitial: loadInitial,
            #showGreetingScreen: showGreetingScreen,
            #scolltoPosition: scolltoPosition,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> checkGreetingScreenOpen(int? index) => (super.noSuchMethod(
        Invocation.method(
          #checkGreetingScreenOpen,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void reStartTutorial() => super.noSuchMethod(
        Invocation.method(
          #reStartTutorial,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.Widget> listNavDestinationItems(
    _i5.BuildContext? context,
    bool? isSelected,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listNavDestinationItems,
          [
            context,
            isSelected,
          ],
        ),
        returnValue: <_i5.Widget>[],
      ) as List<_i5.Widget>);

  @override
  void scrollPositionToBottom(int? index) => super.noSuchMethod(
        Invocation.method(
          #scrollPositionToBottom,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i5.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_1<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i3.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i3.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i8.Future<_i3.ApiResponse<dynamic>>.value(
            _FakeApiResponse_1<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<dynamic>>);

  @override
  _i8.Future<_i3.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i8.Future<_i3.ApiResponse<dynamic>?>.value(),
      ) as _i8.Future<_i3.ApiResponse<dynamic>?>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserGenericProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserGenericProvider extends _i1.Mock
    implements _i13.UserGenericProvider {
  MockUserGenericProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i14.WalletData> get voucherList => (super.noSuchMethod(
        Invocation.getter(#voucherList),
        returnValue: <_i14.WalletData>[],
      ) as List<_i14.WalletData>);

  @override
  int get readNotificationCount => (super.noSuchMethod(
        Invocation.getter(#readNotificationCount),
        returnValue: 0,
      ) as int);

  @override
  int get readTravelCredit => (super.noSuchMethod(
        Invocation.getter(#readTravelCredit),
        returnValue: 0,
      ) as int);

  @override
  bool get listCompanion => (super.noSuchMethod(
        Invocation.getter(#listCompanion),
        returnValue: false,
      ) as bool);

  @override
  bool get walletRedeem => (super.noSuchMethod(
        Invocation.getter(#walletRedeem),
        returnValue: false,
      ) as bool);

  @override
  bool get showDelete => (super.noSuchMethod(
        Invocation.getter(#showDelete),
        returnValue: false,
      ) as bool);

  @override
  bool get is24hrsClockEnable => (super.noSuchMethod(
        Invocation.getter(#is24hrsClockEnable),
        returnValue: false,
      ) as bool);

  @override
  set userModel(_i15.UserModel? _userModel) => super.noSuchMethod(
        Invocation.setter(
          #userModel,
          _userModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set voucherList(List<_i14.WalletData>? _voucherList) => super.noSuchMethod(
        Invocation.setter(
          #voucherList,
          _voucherList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isCompanion(bool? _isCompanion) => super.noSuchMethod(
        Invocation.setter(
          #isCompanion,
          _isCompanion,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set evaIntroNode(String? _evaIntroNode) => super.noSuchMethod(
        Invocation.setter(
          #evaIntroNode,
          _evaIntroNode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set readNotificationCount(int? _readNotificationCount) => super.noSuchMethod(
        Invocation.setter(
          #readNotificationCount,
          _readNotificationCount,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set readTravelCredit(int? _readTravelCredit) => super.noSuchMethod(
        Invocation.setter(
          #readTravelCredit,
          _readTravelCredit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set listCompanion(bool? _listCompanion) => super.noSuchMethod(
        Invocation.setter(
          #listCompanion,
          _listCompanion,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set walletRedeem(bool? _walletRedeem) => super.noSuchMethod(
        Invocation.setter(
          #walletRedeem,
          _walletRedeem,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showDelete(bool? _showDelete) => super.noSuchMethod(
        Invocation.setter(
          #showDelete,
          _showDelete,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set is24hrsClockEnable(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #is24hrsClockEnable,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set setEvaIntroNode(String? value) => super.noSuchMethod(
        Invocation.setter(
          #setEvaIntroNode,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userMatchDetail(_i16.MatchResponse? value) => super.noSuchMethod(
        Invocation.setter(
          #userMatchDetail,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set walletResponse(_i14.WalletResponse? value) => super.noSuchMethod(
        Invocation.setter(
          #walletResponse,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i4.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_2(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i4.AmplifyService);

  @override
  _i5.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_3(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i5.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i4.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i5.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  dynamic updateEvaIntroNode(String? value) =>
      super.noSuchMethod(Invocation.method(
        #updateEvaIntroNode,
        [value],
      ));

  @override
  dynamic changeDelete(bool? val) => super.noSuchMethod(Invocation.method(
        #changeDelete,
        [val],
      ));

  @override
  dynamic updateWalletRedeem(bool? val) => super.noSuchMethod(Invocation.method(
        #updateWalletRedeem,
        [val],
      ));

  @override
  dynamic updateCompanion(bool? val) => super.noSuchMethod(Invocation.method(
        #updateCompanion,
        [val],
      ));

  @override
  void updateUserModel() => super.noSuchMethod(
        Invocation.method(
          #updateUserModel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markNotificationRead() => super.noSuchMethod(
        Invocation.method(
          #markNotificationRead,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserCompanionStatus() => super.noSuchMethod(
        Invocation.method(
          #updateUserCompanionStatus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i5.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_1<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i3.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i3.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i8.Future<_i3.ApiResponse<dynamic>>.value(
            _FakeApiResponse_1<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i8.Future<_i3.ApiResponse<dynamic>>);

  @override
  _i8.Future<_i3.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i8.Future<_i3.ApiResponse<dynamic>?>.value(),
      ) as _i8.Future<_i3.ApiResponse<dynamic>?>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i5.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_4(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i5.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i5.InheritedWidget dependOnInheritedElement(
    _i5.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_5(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i5.InheritedWidget);

  @override
  void visitAncestorElements(_i5.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i5.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i5.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.DiagnosticsNode describeElement(
    String? name, {
    _i17.DiagnosticsTreeStyle? style = _i17.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_6(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  _i5.DiagnosticsNode describeWidget(
    String? name, {
    _i17.DiagnosticsTreeStyle? style = _i17.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_6(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  List<_i5.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i5.DiagnosticsNode>[],
      ) as List<_i5.DiagnosticsNode>);

  @override
  _i5.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_6(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i5.DiagnosticsNode);
}
