# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    # 1. Validate variables (fail fast)
    unless ENV['APP_VERSION'] && ENV['BUILD_NUMBER']
      UI.user_error!("Both APP_VERSION and BUILD_NUMBER must be set as GitLab variables")
    end

    # 2. Validate version format (semver)
    unless ENV['APP_VERSION'].match(/^\d+\.\d+\.\d+$/)
      UI.user_error!("Invalid APP_VERSION format. Use MAJOR.MINOR.PATCH (e.g. 1.2.3)")
    end

    # 3. Validate build number (numeric)
    unless ENV['BUILD_NUMBER'].match(/^\d+$/)
      UI.user_error!("BUILD_NUMBER must be numeric (e.g. 42)")
    end


    keychain_password = ENV['KEYCHAIN_PASSWORD']
    version_number = ENV['APP_VERSION'] || get_version_number(xcodeproj: "Runner.xcodeproj")
    build_number = ENV['BUILD_NUMBER'] || increment_build_number(xcodeproj: "Runner.xcodeproj") 

    unlock_keychain(
      path: "~/Library/Keychains/login.keychain-db",
      password: keychain_password
    )
    match(app_identifier: "com.visa.eva", type: "appstore",readonly:true)

    increment_version_number(
    xcodeproj: "Runner.xcodeproj",
    version_number: version_number  # Use the variable we defined
  )
  
  increment_build_number(
    xcodeproj: "Runner.xcodeproj",
    build_number: build_number  # Use the variable we defined
  )


    # updated_version_number = bump_build_number()
    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "prod")
    login 
    # upload_to_testflight
  end

  desc "Login to App Store Connect"
  lane :login do 
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
    )
  end

  def bump_build_number()
    login
    latest_build_number = latest_testflight_build_number(initial_build_number: 0 )
    return (latest_build_number + 1)
  end
end
