// Mocks generated by Mockito 5.4.6 from annotations
// in visaamigo/test/ui/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter/material.dart' as _i3;
import 'package:flutter/services.dart' as _i15;
import 'package:local_auth/local_auth.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:visaamigo/features/ai_assistant/providers/ai_assistant_main_provider.dart'
    as _i11;
import 'package:visaamigo/features/login/model/login_model.dart' as _i8;
import 'package:visaamigo/features/select_languages/providers/language_selection_generic_provider.dart'
    as _i19;
import 'package:visaamigo/features/signup/model/user_model.dart' as _i9;
import 'package:visaamigo/features/splash_screen/repo/user_detail_repo.dart'
    as _i2;
import 'package:visaamigo/remote/api_client.dart' as _i4;
import 'package:visaamigo/remote/api_response.dart' as _i6;
import 'package:visaamigo/ui/provider/theme_provider.dart' as _i18;
import 'package:visaamigo/ui/userdashboard/user_dashboard_provider.dart'
    as _i17;
import 'package:visaamigo/utils/Inactive_session.dart' as _i14;
import 'package:visaamigo/utils/amplify_service.dart' as _i5;
import 'package:visaamigo/utils/responsive_util.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDetailRepo_0 extends _i1.SmartFake
    implements _i2.UserDetailRepo {
  _FakeUserDetailRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_2 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_3 extends _i1.SmartFake implements _i4.ApiClient {
  _FakeApiClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAmplifyService_4 extends _i1.SmartFake
    implements _i5.AmplifyService {
  _FakeAmplifyService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_5 extends _i1.SmartFake implements _i3.BuildContext {
  _FakeBuildContext_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_6<T> extends _i1.SmartFake
    implements _i6.ApiResponse<T> {
  _FakeApiResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_7 extends _i1.SmartFake implements _i3.Widget {
  _FakeWidget_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [LoginViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginViewModel extends _i1.Mock implements _i8.LoginViewModel {
  MockLoginViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserDetailRepo get userDetailRepo => (super.noSuchMethod(
        Invocation.getter(#userDetailRepo),
        returnValue: _FakeUserDetailRepo_0(
          this,
          Invocation.getter(#userDetailRepo),
        ),
      ) as _i2.UserDetailRepo);

  @override
  _i3.GlobalKey<_i3.FormState> get formKey => (super.noSuchMethod(
        Invocation.getter(#formKey),
        returnValue: _FakeGlobalKey_1<_i3.FormState>(
          this,
          Invocation.getter(#formKey),
        ),
      ) as _i3.GlobalKey<_i3.FormState>);

  @override
  _i3.TextEditingController get pass => (super.noSuchMethod(
        Invocation.getter(#pass),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#pass),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#email),
        ),
      ) as _i3.TextEditingController);

  @override
  bool get isEmailDisable => (super.noSuchMethod(
        Invocation.getter(#isEmailDisable),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoginButtonDisable => (super.noSuchMethod(
        Invocation.getter(#isLoginButtonDisable),
        returnValue: false,
      ) as bool);

  @override
  List<String> get formValid => (super.noSuchMethod(
        Invocation.getter(#formValid),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isDisableField => (super.noSuchMethod(
        Invocation.getter(#isDisableField),
        returnValue: false,
      ) as bool);

  @override
  bool get showError => (super.noSuchMethod(
        Invocation.getter(#showError),
        returnValue: false,
      ) as bool);

  @override
  set pass(_i3.TextEditingController? _pass) => super.noSuchMethod(
        Invocation.setter(
          #pass,
          _pass,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set email(_i3.TextEditingController? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userModel(_i9.UserModel? _userModel) => super.noSuchMethod(
        Invocation.setter(
          #userModel,
          _userModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isEmailDisable(bool? _isEmailDisable) => super.noSuchMethod(
        Invocation.setter(
          #isEmailDisable,
          _isEmailDisable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoginButtonDisable(bool? _isLoginButtonDisable) => super.noSuchMethod(
        Invocation.setter(
          #isLoginButtonDisable,
          _isLoginButtonDisable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set formValid(List<String>? _formValid) => super.noSuchMethod(
        Invocation.setter(
          #formValid,
          _formValid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isBiometricEnable(bool? _isBiometricEnable) => super.noSuchMethod(
        Invocation.setter(
          #isBiometricEnable,
          _isBiometricEnable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorText(String? _errorText) => super.noSuchMethod(
        Invocation.setter(
          #errorText,
          _errorText,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isDisableField(bool? _isDisableField) => super.noSuchMethod(
        Invocation.setter(
          #isDisableField,
          _isDisableField,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showError(bool? _showError) => super.noSuchMethod(
        Invocation.setter(
          #showError,
          _showError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set supportedBiometricsType(_i10.BiometricType? _supportedBiometricsType) =>
      super.noSuchMethod(
        Invocation.setter(
          #supportedBiometricsType,
          _supportedBiometricsType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set aiAssistantMainProvider(
          _i11.AiAssistantMainProvider? _aiAssistantMainProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #aiAssistantMainProvider,
          _aiAssistantMainProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_3(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i4.ApiClient);

  @override
  _i5.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_4(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i5.AmplifyService);

  @override
  _i3.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_5(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i3.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i5.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i3.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> init(
    _i9.UserModel? userEmailModel,
    bool? showBiometrics,
    _i11.AiAssistantMainProvider? aiAssistantMainProvider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [
            userEmailModel,
            showBiometrics,
            aiAssistantMainProvider,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  dynamic validate(String? valid) => super.noSuchMethod(Invocation.method(
        #validate,
        [valid],
      ));

  @override
  dynamic validStateChange(String? valid) =>
      super.noSuchMethod(Invocation.method(
        #validStateChange,
        [valid],
      ));

  @override
  dynamic checkError(String? error) => super.noSuchMethod(Invocation.method(
        #checkError,
        [error],
      ));

  @override
  _i12.Future<bool> canAttemptLogin() => (super.noSuchMethod(
        Invocation.method(
          #canAttemptLogin,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<void> resetLoginAttempts() => (super.noSuchMethod(
        Invocation.method(
          #resetLoginAttempts,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadGreetingScreen() => (super.noSuchMethod(
        Invocation.method(
          #loadGreetingScreen,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void loadHomePage() => super.noSuchMethod(
        Invocation.method(
          #loadHomePage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showAuthenticationDialog(_i3.BuildContext? context) =>
      super.noSuchMethod(
        Invocation.method(
          #showAuthenticationDialog,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> getWalletApi() => (super.noSuchMethod(
        Invocation.method(
          #getWalletApi,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> getMatchApi() => (super.noSuchMethod(
        Invocation.method(
          #getMatchApi,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i6.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i6.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>>.value(
            _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i12.Future<_i6.ApiResponse<dynamic>>);

  @override
  _i12.Future<_i6.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>?>.value(),
      ) as _i12.Future<_i6.ApiResponse<dynamic>?>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [InactivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInactivityService extends _i1.Mock implements _i14.InactivityService {
  MockInactivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get timeoutDuration => (super.noSuchMethod(
        Invocation.getter(#timeoutDuration),
        returnValue: 0,
      ) as int);

  @override
  int get timeoutDurationPopup => (super.noSuchMethod(
        Invocation.getter(#timeoutDurationPopup),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void userInteraction(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #userInteraction,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAppLifecycleState(_i13.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  bool handleStartBackGesture(_i15.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i15.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> didPushRouteInformation(
          _i3.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i13.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i13.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i13.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i12.Future<_i13.AppExitResponse>.value(_i13.AppExitResponse.exit),
      ) as _i12.Future<_i13.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ResponsiveUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponsiveUtil extends _i1.Mock implements _i16.ResponsiveUtil {
  MockResponsiveUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BuildContext get ctx => (super.noSuchMethod(
        Invocation.getter(#ctx),
        returnValue: _FakeBuildContext_5(
          this,
          Invocation.getter(#ctx),
        ),
      ) as _i3.BuildContext);

  @override
  set ctx(_i3.BuildContext? _ctx) => super.noSuchMethod(
        Invocation.setter(
          #ctx,
          _ctx,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set appBarTotalHeight(double? _appBarTotalHeight) => super.noSuchMethod(
        Invocation.setter(
          #appBarTotalHeight,
          _appBarTotalHeight,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_3(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i4.ApiClient);

  @override
  _i5.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_4(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i5.AmplifyService);

  @override
  _i3.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_5(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i3.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i5.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i3.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool kISWeb() => (super.noSuchMethod(
        Invocation.method(
          #kISWeb,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isMobile({_i3.BuildContext? context}) => (super.noSuchMethod(
        Invocation.method(
          #isMobile,
          [],
          {#context: context},
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isTablet({_i3.BuildContext? context}) => (super.noSuchMethod(
        Invocation.method(
          #isTablet,
          [],
          {#context: context},
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isDesktop({_i3.BuildContext? context}) => (super.noSuchMethod(
        Invocation.method(
          #isDesktop,
          [],
          {#context: context},
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isMobileWeb({_i3.BuildContext? context}) => (super.noSuchMethod(
        Invocation.method(
          #isMobileWeb,
          [],
          {#context: context},
        ),
        returnValue: false,
      ) as bool);

  @override
  double getResponsiveWidth(
    _i3.BuildContext? context,
    double? percentage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResponsiveWidth,
          [
            context,
            percentage,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Widget responsiveWrapper({
    required _i3.BuildContext? context,
    required _i3.Widget? mobileView,
    _i3.Widget? tabletView,
    _i3.Widget? desktopView,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #responsiveWrapper,
          [],
          {
            #context: context,
            #mobileView: mobileView,
            #tabletView: tabletView,
            #desktopView: desktopView,
          },
        ),
        returnValue: _FakeWidget_7(
          this,
          Invocation.method(
            #responsiveWrapper,
            [],
            {
              #context: context,
              #mobileView: mobileView,
              #tabletView: tabletView,
              #desktopView: desktopView,
            },
          ),
        ),
      ) as _i3.Widget);

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i6.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i6.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>>.value(
            _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i12.Future<_i6.ApiResponse<dynamic>>);

  @override
  _i12.Future<_i6.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>?>.value(),
      ) as _i12.Future<_i6.ApiResponse<dynamic>?>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserDashboardProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDashboardProvider extends _i1.Mock
    implements _i17.UserDashboardProvider {
  MockUserDashboardProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_3(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i4.ApiClient);

  @override
  _i5.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_4(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i5.AmplifyService);

  @override
  _i3.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_5(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i3.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i5.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i3.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> loadUserDashboard(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadUserDashboard,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadMorePosts(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadMorePosts,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i6.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i6.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>>.value(
            _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i12.Future<_i6.ApiResponse<dynamic>>);

  @override
  _i12.Future<_i6.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>?>.value(),
      ) as _i12.Future<_i6.ApiResponse<dynamic>?>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i18.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  _i3.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setThemeMode(_i3.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SelectLanguageGenericProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectLanguageGenericProvider extends _i1.Mock
    implements _i19.SelectLanguageGenericProvider {
  MockSelectLanguageGenericProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get currentArbData => (super.noSuchMethod(
        Invocation.getter(#currentArbData),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isRTL => (super.noSuchMethod(
        Invocation.getter(#isRTL),
        returnValue: false,
      ) as bool);

  @override
  bool get isDe => (super.noSuchMethod(
        Invocation.getter(#isDe),
        returnValue: false,
      ) as bool);

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  _i4.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_3(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i4.ApiClient);

  @override
  _i5.AmplifyService get amplifyService => (super.noSuchMethod(
        Invocation.getter(#amplifyService),
        returnValue: _FakeAmplifyService_4(
          this,
          Invocation.getter(#amplifyService),
        ),
      ) as _i5.AmplifyService);

  @override
  _i3.BuildContext get mContext => (super.noSuchMethod(
        Invocation.getter(#mContext),
        returnValue: _FakeBuildContext_5(
          this,
          Invocation.getter(#mContext),
        ),
      ) as _i3.BuildContext);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isDesktopView => (super.noSuchMethod(
        Invocation.getter(#isDesktopView),
        returnValue: false,
      ) as bool);

  @override
  bool get isMobileWebView => (super.noSuchMethod(
        Invocation.getter(#isMobileWebView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletView => (super.noSuchMethod(
        Invocation.getter(#isTabletView),
        returnValue: false,
      ) as bool);

  @override
  bool get isTabletWebFromBase => (super.noSuchMethod(
        Invocation.getter(#isTabletWebFromBase),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set amplifyService(_i5.AmplifyService? _amplifyService) => super.noSuchMethod(
        Invocation.setter(
          #amplifyService,
          _amplifyService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoadingMore(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoadingMore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mContext(_i3.BuildContext? value) => super.noSuchMethod(
        Invocation.setter(
          #mContext,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> loadSavedLocale() => (super.noSuchMethod(
        Invocation.method(
          #loadSavedLocale,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> setLanguage(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [code],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadArbFile(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #loadArbFile,
          [langCode],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  String getLocalizedString(
    String? key, {
    String? fallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalizedString,
          [key],
          {#fallback: fallback},
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedString,
            [key],
            {#fallback: fallback},
          ),
        ),
      ) as String);

  @override
  List<String> getAllTranslationKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllTranslationKeys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String getKeyFromValue(String? targetValue) => (super.noSuchMethod(
        Invocation.method(
          #getKeyFromValue,
          [targetValue],
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #getKeyFromValue,
            [targetValue],
          ),
        ),
      ) as String);

  @override
  Map<String, String> getAllTranslations() => (super.noSuchMethod(
        Invocation.method(
          #getAllTranslations,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  bool hasTranslation(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hasTranslation,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearArbCache() => super.noSuchMethod(
        Invocation.method(
          #clearArbCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic navPush(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPush,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navPushReplace(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navPushReplace,
        [name],
        {#extra: extra},
      ));

  @override
  dynamic navGo(
    String? name, {
    Object? extra,
  }) =>
      super.noSuchMethod(Invocation.method(
        #navGo,
        [name],
        {#extra: extra},
      ));

  @override
  void setState() => super.noSuchMethod(
        Invocation.method(
          #setState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.ApiResponse<dynamic> getResponse(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getResponse,
          [key],
        ),
        returnValue: _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getResponse,
            [key],
          ),
        ),
      ) as _i6.ApiResponse<dynamic>);

  @override
  void clearPagination() => super.noSuchMethod(
        Invocation.method(
          #clearPagination,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedItem(dynamic item) => super.noSuchMethod(
        Invocation.method(
          #setSelectedItem,
          [item],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i6.ApiResponse<dynamic>> getData({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    bool? isPaginated = false,
    bool? isDataNodePresent = true,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #headers: headers,
            #queryParameters: queryParameters,
            #isPaginated: isPaginated,
            #isDataNodePresent: isDataNodePresent,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>>.value(
            _FakeApiResponse_6<dynamic>(
          this,
          Invocation.method(
            #getData,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #responseKey: responseKey,
              #headers: headers,
              #queryParameters: queryParameters,
              #isPaginated: isPaginated,
              #isDataNodePresent: isDataNodePresent,
              #showLoader: showLoader,
            },
          ),
        )),
      ) as _i12.Future<_i6.ApiResponse<dynamic>>);

  @override
  _i12.Future<_i6.ApiResponse<dynamic>?> loadMore({
    required String? endpoint,
    required dynamic Function(Map<String, dynamic>)? fromJson,
    required String? responseKey,
    required String? itemsKey,
    required int? nextPage,
    int? dataLimit = 6,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #responseKey: responseKey,
            #itemsKey: itemsKey,
            #nextPage: nextPage,
            #dataLimit: dataLimit,
            #headers: headers,
          },
        ),
        returnValue: _i12.Future<_i6.ApiResponse<dynamic>?>.value(),
      ) as _i12.Future<_i6.ApiResponse<dynamic>?>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
